### ISSUE TITLE
installation errors - how to install ??

### ISSUE THREAD

**Issue by CDahmsCellarEye** [mrin9/RapiPdf#44]
I'm using Ubuntu 18.04.  Initially I did:

```
cd ~
sudo apt-get install yarn
git clone https://github.com/mrin9/RapiPdf.git
cd RapiPdf
```

Received this error:

`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'`

Based on this post:

`https://stackoverflow.com/questions/46013544/yarn-install-command-error-no-such-file-or-directory-install`

I next did:

```
sudo apt remove cmdtest
sudo apt remove yarn
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update
sudo apt-get install yarn
cd RapiPdf/
yarn install
```

Now I get this error:

```
yarn install v1.22.4
[1/4] Resolving packages...
warning babel-loader > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
warning webpack > mkdirp@0.5.4: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
[2/4] Fetching packages...
error marked@0.8.2: The engine "node" is incompatible with this module. Expected version ">= 8.16.2". Got "8.10.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

This post seems to mention this error:

`https://github.com/babel/babel-loader/issues/833`

However I have no idea what `mkdirp` is or how to update it on Ubuntu 18.04 if that is even possible.

Suggestions ??

Note: this questions is similar to one I posted for RapiDoc @ https://github.com/mrin9/RapiDoc/issues/167

--- edit ---

If I do:

```
cd ~
cd RapiPdf
npm install
```

I get:

```
$ npm install
loadDep:swagger2openapi → ▌ ╢████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm ERR! Linux 5.0.0-37-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cdahms/RapiPdf/npm-debug.log
```

Full log attached per error message instructions.

Suggestions??

[npm-debug.log](https://github.com/mrin9/RapiPdf/files/4406128/npm-debug.log)

**Comment by CDahmsCellarEye** [comment]
This now contains the solution:

https://github.com/mrin9/RapiDoc/issues/167
