### ISSUE TITLE
How to use RapiPdf to view local OpenAPI .json files ??

### ISSUE THREAD

**Issue by CDahmsCellarEye** [mrin9/RapiPdf#45]
After troubleshooting some installation concerns, I'm now able to get the build process completed successfully:

```
cd ~/RapiPdf
yarn install
yarn build
```

I get this crazy looking browser window:

![crazy](https://user-images.githubusercontent.com/58487204/77991896-d1b52200-72d9-11ea-8afb-a07f72f75de5.png)

I'm not sure what to make of this.  In any case if I continue on with the commands in the readme:

`yarn serve`

I get this:

```
$ yarn serve
yarn run v1.22.4
$ webpack-dev-server --mode=development
events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1309:16)
    at listenInCluster (net.js:1357:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1496:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:69:10)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1336:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: 'EADDRINUSE',
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

In the event I accidentally started some other process on port 8080 and forgot about it, I rebooted and tried the `yarn serve` command again and received same error.

How can I proceed to use this repository to view a local OpenAPI .json file?

**Comment by CDahmsCellarEye** [comment]
I found the reason I was getting the above error was Docker was running and taking up 127.0.0.1:8080, I uninstalled Docker, rebooted, and now this error is resolved
